name: test-box

on:
  workflow_call:

jobs:
  test_box_setup_and_run:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build container
        run: |
          docker build . -t test-box-${{ github.sha }}

      - name: Run Container
        run: |
          docker run --rm test-box-${{ github.sha }}

      - name: Cleanup Container
        if: always()
        run: |
          docker rmi test-box-${{ github.sha }}
